export const enum COLORS {
  DARK_MINT = '#0E8388',
  MEDIUM_MINT = '#63CBCC',
  LIGHT_MINT = '#CFF1F3',
  WHITE_COLOR = '#FFFFFF',
  LIGHT_GREY = '#DADADA',

  TRANSPARENT_WHITE = '#FFFFFF44',

  LIGHT_SHADOW = '#00000044',
}
