export const enum COLORS {
  DARK_MINT = '#0E8388',
  MEDIUM_MINT = '#63CBCC',
  WHITE_COLOR = '#FFFFFF',
  LIGHT_GREY = '#DADADA',

  TRANSPARENT_WHITE = '#FFFFFFFF44',

  LIGHT_SHADOW = '#00000044',
}
